# Generated by Django 5.1.6 on 2025-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_user_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
